arm_node:
  ros__parameters:
    names: [ "J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2" ]
    families: [ "HEBIArm" ]
    gains_package: "hebi_description"
    gains_file: "config/gains/A-2085-05_gains.xml"
    hrdf_package: "hebi_description"
    hrdf_file: "config/hrdf/A-2085-05.hrdf"
    home_position: [ 0.01, 2.09, 2.09, 0.0, 1.5707963]
