arm_node:
  ros__parameters:
    names: [ "J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3" ]
    families: [ "Arm" ]
    gains_package: "hebi_description"
    gains_file: "config/gains/A-2240-06_gains.xml"
    hrdf_package: "hebi_description"
    hrdf_file: "config/hrdf/A-2240-06.hrdf"
    home_position: [ 0.6, 0.15, -2.85, 0.01, -1.5708, 0.01 ]
